# Generated by Django 3.0.7 on 2022-03-22 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
