# Generated by Django 3.0.7 on 2022-03-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditentry_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditentry',
            old_name='datetime',
            new_name='time',
        ),
    ]
